### ISSUE TITLE
[BUG] 'IVRCSdkWorldBuilderApi' error on VRC SDK 3.10.3, cannot launch unity. PC, fresh project.

### ISSUE THREAD

**Issue by micksam7** [Mattshark89/OpenFlight-VRC#205]
**Describe the bug**
On a completely fresh project, Unity prompts to go into Safe Mode and spills out the error
`Packages\com.mattshark.openflight\Editor\TagNotifier.cs(36,50): error CS0246: The type or namespace name 'IVRCSdkWorldBuilderApi' could not be found (are you missing a using directive or an assembly reference?)`

**To Reproduce**
1. Start a new project
2. Include the latest non-beta SDK, 3.10.3
3. Include openflight

**Expected behavior**
Unity launches

**Screenshots**
<img width="2346" height="400" alt="Image" src="https://github.com/user-attachments/assets/97910e4d-2eca-4136-9675-36f5532989af" />

**Desktop (please complete the following information):**
 - OS: Windows 11
 - VRC SDK Version: 3.10.3

**Additional context**
Works fine on SDK 3.10.2
Works fine on SDK 3.10.4-beta.3
